package db

import (
	"flag"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

var updateSchemaSnapshot = flag.Bool("update", false, "update schema snapshot golden files")

func TestSchemaSnapshot(t *testing.T) {
	d := openSchemaSnapshotDB(t)
	got := dumpSchemaSnapshot(t, d)
	snapshotPath := filepath.Join("testdata", "schema_snapshot.sql")

	if *updateSchemaSnapshot {
		if err := os.MkdirAll(filepath.Dir(snapshotPath), 0o755); err != nil {
			t.Fatalf("create schema snapshot dir: %v", err)
		}
		if err := os.WriteFile(snapshotPath, []byte(got), 0o644); err != nil {
			t.Fatalf("write schema snapshot: %v", err)
		}
		return
	}

	want, err := os.ReadFile(snapshotPath)
	if err != nil {
		t.Fatalf("read schema snapshot: %v\nRun: go test ./internal/db -run TestSchemaSnapshot -update -count=1", err)
	}
	if got != string(want) {
		t.Fatalf("schema snapshot drift\nRun: go test ./internal/db -run TestSchemaSnapshot -update -count=1")
	}
}

func TestSchemaTableLifecyclesCoverFreshSchema(t *testing.T) {
	d := openSchemaSnapshotDB(t)
	tables := freshSchemaTableNames(t, d)
	freshTables := make(map[string]bool, len(tables))
	for _, table := range tables {
		freshTables[table] = true
	}

	var missing []string
	for _, table := range tables {
		lifecycle, ok := schemaTableLifecycles[table]
		if !ok {
			missing = append(missing, table)
			continue
		}
		if lifecycle == "" {
			t.Fatalf("table %s has empty lifecycle", table)
		}
	}

	var extra []string
	for table := range schemaTableLifecycles {
		if !freshTables[table] {
			extra = append(extra, table)
		}
	}
	sort.Strings(missing)
	sort.Strings(extra)
	if len(missing) > 0 || len(extra) > 0 {
		t.Fatalf("schema lifecycle coverage mismatch\nmissing: %v\nextra: %v", missing, extra)
	}
}

func TestSchemaTableLifecycleClassifications(t *testing.T) {
	want := map[string]schemaTableLifecycle{
		"assets":              schemaLifecycleMaintainedState,
		"android_sync_assets": schemaLifecycleDerivedCache,
		"bookmarks":           schemaLifecycleUserState,
		"download_queue":      schemaLifecycleQueue,
		"feed_items":          schemaLifecycleArchive,
		"schema_migrations":   schemaLifecycleLegacyMigration,
	}
	for table, lifecycle := range want {
		if got := schemaTableLifecycles[table]; got != lifecycle {
			t.Fatalf("schema lifecycle for %s = %q, want %q", table, got, lifecycle)
		}
	}
}

func openSchemaSnapshotDB(t *testing.T) *DB {
	t.Helper()
	tmpDir := t.TempDir()
	d, err := Open(filepath.Join(tmpDir, "igloo.db"), filepath.Join(tmpDir, "data"))
	if err != nil {
		t.Fatalf("open schema snapshot db: %v", err)
	}
	t.Cleanup(func() {
		if err := d.Close(); err != nil {
			t.Fatalf("close schema snapshot db: %v", err)
		}
	})
	return d
}

func freshSchemaTableNames(t *testing.T, d *DB) []string {
	t.Helper()
	rows, err := d.conn.Query(`
		SELECT name
		FROM sqlite_master
		WHERE type = 'table'
		  AND name NOT LIKE 'sqlite_%'
		ORDER BY name
	`)
	if err != nil {
		t.Fatalf("query schema tables: %v", err)
	}
	defer func() {
		_ = rows.Close()
	}()

	var tables []string
	for rows.Next() {
		var table string
		if err := rows.Scan(&table); err != nil {
			t.Fatalf("scan schema table: %v", err)
		}
		tables = append(tables, table)
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("iterate schema tables: %v", err)
	}
	return tables
}

func dumpSchemaSnapshot(t *testing.T, d *DB) string {
	t.Helper()

	rows, err := d.conn.Query(`
		SELECT type, name, tbl_name, sql
		FROM sqlite_master
		WHERE type IN ('table', 'index', 'trigger')
		  AND sql IS NOT NULL
		  AND name NOT LIKE 'sqlite_%'
	`)
	if err != nil {
		t.Fatalf("query sqlite_master: %v", err)
	}
	defer func() {
		_ = rows.Close()
	}()

	type schemaEntry struct {
		typ   string
		name  string
		table string
		sql   string
	}
	var entries []schemaEntry
	for rows.Next() {
		var entry schemaEntry
		if err := rows.Scan(&entry.typ, &entry.name, &entry.table, &entry.sql); err != nil {
			t.Fatalf("scan sqlite_master: %v", err)
		}
		entry.sql = normalizeSchemaSQL(entry.sql)
		entries = append(entries, entry)
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("iterate sqlite_master: %v", err)
	}

	sort.Slice(entries, func(i, j int) bool {
		if entries[i].typ != entries[j].typ {
			return entries[i].typ < entries[j].typ
		}
		if entries[i].name != entries[j].name {
			return entries[i].name < entries[j].name
		}
		return entries[i].table < entries[j].table
	})

	var b strings.Builder
	b.WriteString("-- Code generated by TestSchemaSnapshot. DO NOT EDIT.\n")
	b.WriteString("-- Update with: go test ./internal/db -run TestSchemaSnapshot -update -count=1\n\n")
	for i, entry := range entries {
		if i > 0 {
			b.WriteByte('\n')
		}
		b.WriteString("-- ")
		b.WriteString(entry.typ)
		b.WriteString(": ")
		b.WriteString(entry.name)
		b.WriteString(" on ")
		b.WriteString(entry.table)
		b.WriteByte('\n')
		b.WriteString(entry.sql)
		b.WriteString(";\n")
	}
	return b.String()
}

func normalizeSchemaSQL(sql string) string {
	return strings.Join(strings.Fields(sql), " ")
}
